name: 'Cache'
description: 'Cache artifacts like dependencies and build outputs to improve workflow execution time'
author: 'GitHub'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache and restore'
    required: true
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.'
    required: false
  endpoint:
    description: 'The endpoint for the cache object service'
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
branding:
  icon: 'archive'
  color: 'gray-dark'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_KEY: ${{ inputs.key }}
    INPUT_RESTORE_KEYS: ${{ inputs.restore-keys }}
    INPUT_ENDPOINT: ${{ inputs.endpoint }}