name: 'Restore a cache'
description: 'Restore Cache artifacts like dependencies and build outputs to improve workflow execution time'
author: 'Mark Wolfe'
inputs:
  path:
    description: 'A list of files, directories, and wildcard patterns to cache'
    required: true
  key:
    description: 'An explicit key for saving the cache'
    required: true
  endpoint:
    description: 'The endpoint for the cache object service'
    required: false    
runs:
  using: docker
  image: ../Dockerfile
  args:
    - restore
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_KEY: ${{ inputs.key }}
    INPUT_ENDPOINT: ${{ inputs.endpoint }}    
branding:
  icon: 'archive'
  color: 'gray-dark'